### ISSUE TITLE
Publications - Multiple DOIs

### ISSUE THREAD

**Issue by parsr** [artudis-utils/dashboard#14]
Same DOI Multiple Publications

Can we report / group by type (where dups grouped by content types they are part of).

Articles
-- dups..

Book Chapters
-- dups

etc.

**Comment by cudevmaxwell** [comment]
Done, kind of. 

I now do a check for same type and same DOI, instead of just on DOI. 

This eliminates the problems with Books and Book Chapters having the same DOI. We care more about two articles having the same DOI, or two Books having the same DOI.
