### ISSUE TITLE
New tests

### ISSUE THREAD

**Issue by parsr** [artudis-utils/dashboard#17]
Two new tests to add.

For Orgs
*  need to flag Orgs having  identifier values with "scheme": "youtube" but NO  "scheme": "isni" in same record

For Persons
* need to flag PPL having ("scheme": "youtube" or "youtube_channel") but no "scheme": "isni"

not sure, but don't think there are any currently matching person case above -- but still need to flag in case it comes up.

**Comment by cudevmaxwell** [comment]
Fixed in d1bbb2ec5497aee6a6bc0a54ffc28f5683c5630e and e45870d7885feee5ae9216debc7196977413227b
