### ISSUE TITLE
Publication stats

### ISSUE THREAD

**Issue by parsr** [artudis-utils/dashboard#20]
For recently added dashboard code, perhaps we should include count of  pubs where 
"open_access": "true"

https://github.com/artudis-utils/dashboard/blob/master/main.js#L925

**Comment by parsr** [comment]
Or even ideally we'd distinguish between count of OA is true (hosted vs. virtual)

**Comment by cudevmaxwell** [comment]
Added a new output box, here's today's output:

Total number of attachments →
4443

Open Access and File Access to Number of Attachments →
oa:true-link:false-file:true - 1853
oa:true-link:true-file:false - 776
oa:false-link:false-file:true - 760
oa:false-link:true-file:false - 1030
oa:true-link:true-file:true - 6
oa:false-link:false-file:false - 6
oa:false-link:true-file:true - 11
oa:true-link:false-file:false - 1
