### ISSUE TITLE
Publications check - erratum

### ISSUE THREAD

**Issue by parsr** [artudis-utils/dashboard#21]
New issue - Erratum should have reciprocal link with the original publication. We don't have very many, but of the couple of dozen, it would be nice to add to our integrity checks.

Example with See also link (from Erratum to original paper): https://ir.library.carleton.ca/pub/22553/
Example without link: https://ir.library.carleton.ca/pub/4957

From sample 'erratum' keyword filter (https://ir.library.carleton.ca/#filter=all:erratum) would be good to know which Erratum have been published with no relation link back to original publication.

e.g. if string found then don't report, but if no relation string data in 'erratum' metadata, list link to those publications for CMD.  

"relation": [
    {
      "publication": "@Publication:6983", 
      "role": "seeAlso"
    }

**Comment by cudevmaxwell** [comment]
Done! A new check has been added which checks to see if a pub's title starts with 'erratum'. If it does, and it does not contain a relation of role 'seeAlso', output it. 

![image](https://user-images.githubusercontent.com/1489722/91196479-324d5d00-e6c8-11ea-85a9-e04c46d7bdb1.png)

**Comment by parsr** [comment]
Perfect - confirm it works like a charm.
