### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by cudevmaxwell** [artudis-utils/dashboard#6]
This project needs code refactoring. 

1. `typeof VAR !== 'undefined' && VAR.length > 0` is messy and repeated all over the place .
2. Calls to `addOutput()` are too long. Can be cleaned up.

**Comment by jamesmulvenna** [comment]
Cleaned up (1), talked to Kevin about (2) and its not really possible

**Comment by cudevmaxwell** [comment]
Fixed by @jamesmulvenna
