### ISSUE TITLE
Organisations - check for no publications enhancement

### ISSUE THREAD

**Issue by parsr** [artudis-utils/dashboard#7]
Some organization units (smaller labs & centres) don't have publications in their org listing - this can be because it is a newly formed entity, or because those affiliated researchers publish under their "home" department name rather than the smaller lab name, and/or could be a result of org id ambiguity etc.

Need to be able to identify organizations with no "owned" / affiliated publications in the repository.

**Comment by parsr** [comment]
Just thought of a simpler first solution - need Organisations without a Scopus org id -  this will do it, because if there's no scopus identifier with the org record, there shouldn't be any pubs (and if there are pubs, they've been manually assigned to that org and we'll still want to flag these for that additional reason too).  

So we do it on no Scopus identifier only.

Additionally - could you drop the "Organizations without a description" output to the end of org checks listing.  thx

**Comment by jamesmulvenna** [comment]
organizations with no scopus id, and dropped orgs w/o description (DONE)

**Comment by cudevmaxwell** [comment]
Fixed by @jamesmulvenna
